- CHANGELOG.md
- models/asset.go
- tests/tests.go
This patch introduces new resized target option "w400" to improve
the hero image utilization.
> Add new resized target option "w400"

- README.md
- controllers/membership.go
- controllers/subscription.go
- membership_user.sql
- models/subscription.go
- storage/membership.go
- storage/subscription.go
- tests/controller_subscriptions_test.go
- tests/main_test.go
- tests/tests.go
@babygoat  
There are two new endpoints for creating/reading web push subscription.
One is **POST** method for creating a web push subscription,
another is **GET** method for reading a web push subscription.
JSON example:
```
{
"endpoint": "https://fcm.googleapis.com/fcm/send/f4Stnx6WC5s:APA91bFGo-JD8bDwezv1fx3RRyBVq6XxOkYIo8_7vCAJ3HFHLppKAV6GNmOIZLH0YeC2lM_Ifs9GkLK8Vi_8ASEYLBC1aU9nJy2rZSUfH7DE0AqIIbLrs93SdEdkwr5uL6skPMjJsMRT",
"keys":"{\"p256dh\":\"BDmY8OGe-LfW0ENPIADvmdZMo3GfX2J2yqURpsDOn5tT8lQV-VVHyhRUgzjnmx_RRoobwdLULdBr26oULtLML3w\",\"auth\":\"P_AJ9QSqcgM-KJi_GRN3fQ\"}",
"user_id": "1",
"expirationTime": "1526457025"
}
```
**204** Created
**400** Bad request
**409** Duplicate record(depends on `endpoint` value)
**500** Internal server error
Query example: …
> New endpoint for subscribing webpush notification

- .circleci/config.yml
The latest version of kubectl(v1.11.0) breaks the circleci builds.
Before our containers upgrades to v1.11.0, we install kubectl clients according to cluster kubectl version.
@babygoat
> Fix circleci build failing. Install corresponding kubectl pkg version

- .circleci/config.yml
This patch ports the circle-config fixes from twreporter-react repo
for following error.
* Missing CLUSTER_NAME environment variable in "kubectl install" step.
* Fetch the master node version of the cluster instead as there might
exist multiple versions within clusters.
> Fix circle-ci config

- controllers/donation.go
This patch sets the missing field `amount` when creating the draft token
record.
> Fix missing field in token draft record

- controllers/donation.go
This patch adds the fix of incorrect parsing of timestamp with unit
millisecond. Previous work treats the millisecond as nanosecond.
> Fix incorrect parsing of timestamp

- controllers/donation.go
This patch fixes the panic during the donation test results from invalid
memory access(nil).
> Fix invalid memory access during donation test

- controllers/donation.go
This patch changes the tappay request fields `cardholder.name` and
`cardholder.phonenumber` from presenting if provided by client to always
sending these fields.
> Adapt tappay request fields

- routers/router.go
This patch changes the session cookies domain to `.twreporter.org`
rather than default setting (HOST header in default request)
> Change session cookie domain

- .gitignore
- Makefile
- configs/config.go
- dev-env-setup/docker-compose.yml
- dev-env-setup/mysql/Dockerfile
- dev-env-setup/mysql/initdb.sh
- dev-env-setup/mysql/mysql.cnf
@babygoat @YuCJ 
If we want to quickly set up a development environment,
we can easily run `make env-up` in cmd.
and `make env-down` to stop the development environment.
> update development environment setup. build the dev mysql env on the fly

- middlewares/jwt.go
- routers/router.go
Panic will arise when type assertion.
Since the following code didn't work,
`user.(*jwt.Token).Claims.(utils.IDTokenJWTClaims)`,
we may need to find another way to check IDTokenJWTClaims's validation.
However, if we change the code back to previous commit, like below,
`user.(*jwt.Token).Claims.(jwt.MapClaims)`,
it does the same thing(parse JWT and check its validation)
what `CheckJWT` already does.
Hence, remove ValidateIDToken function before we find another way
to check IDTokenJWTClaims's validation.
@babygoat
> hot fix(bug). remove middlewares.jwt.ValidateIDToken

- controllers/account.go
This patch fixes `ActivateLink` with unescaped characters.
@babygoat
> Bug fix. Escape query param in `ActivateLink`

- CHANGELOG.md
- storage/post.go
- storage/topic.go
Behavior: 
We can fetch draft pots/topics from staging-go-api.twreporter.org.
Reason:
In the latest configs, the environment could be `development`, `staging` or `production`.
However, the codes only prevent `production` environment from fetching draft topics/posts.
Hence, in the `staging` environment, we could fetch the drat ones.
Only allow development environment to return draft posts/topics.
> Only development environment can return draft posts or topics

- .circleci/config.yml
- glide.lock
- glide.yaml
This patch updates the go vendor package to the lastest commit. Majorly
, the changes are to adopt the fix in gorm@1.9.2.
> Update go vendor package version

- controllers/donation.go
- models/donation.go
- tests/controller_donations_test.go
This patch fixes the incorrect schemas of pay_by_card_token_donations.
It results from the incorrect placement of `PayInfo` model which should
be specifc fields within pay_by_prime_donations model.
> Fix incorrect schema during donation test

- controllers/donation.go
This patch validate the transaction time field of the tappay response to
fix the invalid datetime format to database.
> Fix missing transaction time when transaction fail

- .circleci/config.yml
This patch disables the docker layer caching as the CircleCI pricing
plan change with the no free plan DLC support.
> Disable Docker Layer Caching

- .circleci/config.yml
This patch fixes the error of incorrect image overwritting owing to
wrong name target configuration.
> Do not overwrite the default image name

- CHANGELOG.md
This patch adds the CHANGELOG for 6.0.0 release. Also, rewrite the
CHANGELOG with following categories
api/
auth(including both email login and oauth)
user(including bookmark)
news (including post, topic, index_page, search, author etc)
webpush
donation
doc
core
* api/[routes group]: includes the changes(fix, new feature) in each route
group.
* doc: includes the changes to README and api documents.
* core: includes the changes to core functions but not related to the
specific routes.
Also use following command for generating commit hash for changes
```
git log --pretty='format:-
[[%C(auto)%h](https://github.com/twreporter/go-api/commit/%H)] -
%s(%an)' [PREVIOUS_COMMIT_HASH]...[CURRENT_COMMIT_HASH] --no-merges
```
> Add CHANGLELOG for 6.0.0 release

- internal/news/model.go
This patch fixes the video bson document decoder which should decode
`filetype`, `size`, `url` fields from the nested `video` document
i.e,
{...
"leading_video": {
"_id": ObjectID(...),
"title": title,
"video": {
"filetype": ...,
"size": ...,
"url": ...,
}
}
...
}
> api/news: fix video bson document decoder

- CHANGELOG.md
Release go-api v6.1.2 with following Changes.
- api/news:
- fix out of order related documents
- fix out of order designers/engineers/photographers/writers
> Release v6.1.2

- membership_user.sql
So far, `twreporter/environment-setup`  builds local mysql database with `membership_user.sql` schema.
However, `membership_user.sql` is out of date.
Those new migrations are not applied to it.
This PR is to update the new schema.
> fix: update membershio_user.sql to catch up the latest migrations

- CHANGELOG.md
Release go-api v6.1.3 with following changes
- api/donation:
- add receipt_header to pay_by_prime_donation,
pay_by_other_method_donation, periodic_donation tables
([#406](https://github.co
m/twreporter/go-api/pull/406))
- api/mail:
- update personal info reveal in donation success email
([#409](https://github.com/twreporter/go-api/pull/409))
> Release v6.1.3

- .circleci/config.yml
This patch workarounds the configMapGenerator issue which does not
quote the numeric value properly during merge operation.
> chore: workaround configMapGenerator issue

- CHANGELOG.md
This patch releases go-api@v6.2.0 with following changes.
- core:
- rename module to github
host([#416](https://github.com/twreporter/go-api/pull/416))
- chore:
- fix configGenerator issue during
CI([#423](https://github.com/twreporter/go-api/pull/423))
- api/donation:
- return error if patch record
failed([#418](https://github.com/twreporter/go-api/pull/418))
- api/news:
- add /v2/authors, /v2/authors/:author_id,
/v2/authors/:author_id/posts
route([#419](https://github.com/twreporter/go-api/pull/419),
[#420](https://github.com/twreporter/go-api/pull/420))
> Release v6.2.0

- controllers/donation.go
This patch logs the information of the donor which cannot be parsed
correctly and the detail can be utilized to provide instructions to the
donors.
> api/donation: log donor info if the update occurs error

- controllers/oauth.go
This patch adds the error log if the session used for the oauth
verification cannot be preserved. With the error log, the error can be
reported by the google cloud error reporting service so that it can be
handled as soon as possible.
> api/auth: log error if the session cannot be saved

- controllers/donation.go
This patch correct the time filter(start_time/end_time) unit which
should be millisecond rather than second.
ref: https://docs.tappaysdk.com/tutorial/zh/reference.html#time
Also, increase the time filter range to 90 days according to the document
ref: https://docs.tappaysdk.com/tutorial/zh/reference.html#time-filter
> api/donation: fix time filter unit

- CHANGELOG.md
This patch updates the CHANGELOG.md to include the changes and commits
of v7.0.0
> chore: release v7.0.0

- CHANGELOG.md
This patch appends the change description for deprecation of v1 news
endpoints.
> doc: add missing change for v7.0.0

- .circleci/config.yml
- Dockerfile
This patch add pubsub credentials to go-api image
- var `PUBSUB_CREDENTIALS` is defined in circleci env
> fix: add pubsub credentials

- doc/index.html
- doc/periodic-donation.apib
- doc/prime-donation.apib
This patch fixes typo `auto_tax_dedution` -> `auto_tax_deduction` for
periodic-donation, prime-donation.
> api/doc: fix typo for `auto_tax_deduction`

- .circleci/config.yml
We move gcp releated credentials/vars into `twreporter-gcp` context.
This patch update accessing context name for accessing gcp related credentials.
> fix: use twreporter-gcp context for gcp related credential

- internal/mongo/document.go
[沒有分類組合的文章，頁面會呈現 404](https://app.asana.com/0/0/1204213366816443/f)
`$unwind` would drop record when target field is null ([ref](https://www.mongodb.com/docs/manual/reference/operator/aggregation/unwind/#field-path-operand))
add `preserveNullAndEmptyArrays` option to `$unwind` to preserve records.
> fix: /posts endpoint return 404 if post.caetgory_set is empty

- controllers/account.go
- controllers/oauth.go
- doc/auth.apib
- doc/oauth.apib
[[會員制] 登入＆註冊的 flow：API 串接](https://app.asana.com/0/1203699264568808/1204699268404621/f)
- oauth
- add onboarding url if user activated && frontend provide onboarding parameter to oauth api
- auth by email
- signin
- same rule as `oauth`
- authentication
- do not add onboarding url even if onboarding parameter is provided
N/A
generate doc/index.html after approved
> feat: support onboarding url on oauth & signin api

- storage/user.go
The role replacement query has reserved world `key` should be specified as a column name.
> fix: Fix role replacement query

- controllers/account.go
- controllers/user.go
The Explorer role mail should be sent if only the user is activated and not already an Explorer.
Due to activated which is set after onboarding, move role mail from signin to setUser.
> fix: move role mail from signin to setUser

- controllers/user.go
The Explorer role was assigned while user created.  So we should send role mail if it is explorer. (not blocking it)
> fix: only send Explorer role mail if is Explorer

- template/role-trailblazer.tmpl
The string replacement keyword in Trailblazer mail is incorrect.
---
- https://app.asana.com/0/0/1205281535004071
> fix: replacement keyword

- controllers/account.go
- controllers/user.go
- routers/router.go
[[維運] onboarding 完，沒辦法維持登入狀態
](https://app.asana.com/0/1203699264568808/1205329976326260/f)
- add `/v2/onboarding` route & set `activated` cookie in response
- api doc & test would be updated in next PR
N/A
> fix: add onboarding route & set cookie after onboarding

- CHANGELOG.md
go-api v7.3.0 release for 支持方案
[cloudsql/membership/update_roles](https://github.com/twreporter/migration-history/tree/master/cloudsql/membership/update_roles)
> chore: bump version to v7.3.0

- CHANGELOG.md
- controllers/oauth.go
Some users can not pass oAuth authentication due to 
"oauth fails due to database operation error:: Error 1406: Data too long for column 'picture' at row 1" error.
Here are the error logs:
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22coastal-run-106202%22%0Aresource.labels.location%3D%22asia-east1%22%0Aresource.labels.cluster_name%3D%22twreporter%22%0Aresource.labels.namespace_name%3D%22production%22%0Alabels.k8s-pod%2Frun%3D%22go-api%22%20severity%3E%3DDEFAULT%0AjsonPayload.message%3D%22oauth%20fails%20due%20to%20database%20operation%20error::%20Error%201406:%20Data%20too%20long%20for%20column%20'picture'%20at%20row%201%22;cursorTimestamp=2023-09-01T13:40:11.410352139Z;aroundTime=2023-09-01T13:40:11.410352139Z;dura …
> fix: quick fix oAuth authentication failures

- controllers/donation.go
The role mail will be sent even if LinePay failed.
Fix the issue by send mail only after `primeDonation.Status == statusPaid`
> fix: only send role mail after success payment

- CHANGELOG.md
- template/success-donation.tmpl
贊助成功信件的「訂閱電子報」連結失效，需要替換成新的網址。
https://app.asana.com/0/0/1206211289316588/f
> fix: wrong email subscription url in success-donation.tmpl

- CHANGELOG.md
- template/success-donation.tmpl
贊助成功信件的「訂閱電子報」連結失效，需要替換成新的網址。
https://app.asana.com/0/0/1206211289316588/f
此 PR 是一個 hotfix，同步發了另一個 PR https://github.com/twreporter/go-api/pull/650 去更新 master branch。
> hotfix: wrong email subscription in donation success email

- storage/analytics.go
/reading-footprint endpoint should only return current 6 month data
N/A
> fix: get current 6 month footprints only

- internal/mongo/document.go
- internal/mongo/operator.go
[[defect] 我的閱讀頁存在後台不存在的後續追蹤內容](https://app.asana.com/0/1203699264568808/1207764753093382/f)
- `$exists: true` would return empty array, need to add `$not: { $size: 0 }` rule
N/A
> fix: `/post_followups` would return empty data

- template/signin-otp.tmpl
[[defect] footer的文字超連結不應有底線](https://app.asana.com/0/1203699264568808/1208279921606021/f)
N/A
> fix: remove text decoration style in chrome

- configs/config.go
- internal/graphql/method.go
[[會員管理 CMS GQL] 產生內部 ip，讓 go-api 可以走內網 request GQL server，以避免 IAP 阻擋。 
](https://app.asana.com/0/1205812314629275/1208386531521148/f)
related to kybernetes-config [#65](https://github.com/twreporter/kubernetes-config/pull/65)
> fix: add `Host` header for IAP issue

- internal/graphql/client.go
address IAP isuue in [[電子收據] go-api 對接 member cms ](https://app.asana.com/0/1203699264568808/1208301216504807/f)
ref: http package [doc](https://pkg.go.dev/net/http#Header.Set)
N/A
> fix: use `Header.Set` instead of `Header.Add` for testing

- controllers/donation.go
- controllers/mail.go
`pangolin` cannot send thank you mail
[[defect] 修復定期定額第二次之後的扣款通知](https://www.notion.so/twreporter/Copyright-2025-67bdec71d7eb42ef9626cae84d013cd7?pvs=4)
- #789 adds new required parameter `donation_type_en` for thank you mail endpoint, but pangolin do not add it in request.
N/A
> fix: get filename from donation type
