twreporter/go-api

Makefile
README.md
configs/config.example.json
dev-env-setup/docker-compose.yml
dev-env-setup/wait-for-it.sh

Provide development environment by using docker-compose

---

CHANGELOG.md
membership_user.sql
models/subscription.go

Update membership_user.sql. Remove soft delete on web_push_subscriptions table

---

CHANGELOG.md

This patch bumps the version to 2.1.1 to consolidate the version
number to staging.

Bump version to 2.1.1

---

controllers/subscription.go
membership_user.sql
models/subscription.go
storage/bookmark.go
storage/errors.go
storage/membership.go
storage/subscription.go

[Performance] Replace md5 hash function by crc32 on subscriptions table

---

CHANGELOG.md
controllers/author.go
controllers/controller-factory.go
controllers/membership.go
controllers/news.go
glide.lock
glide.yaml
models/asset.go
storage/author.go
storage/news.go

@babygoat 
In order to let @YuCJ implement cron job to update algolia, we provide authors information by `/v1/authors{?limit,offset,sort}[GET]` endpoint.

[feature] /v1/authors{?limit,offset,sort}[GET] endpoint for fetching authors

---

.circleci/config.yml
tests/tests.go
utils/db.go

fix(circleci:unexpected build fail)

---

configs/config.go
controllers/oauth.go
routers/router.go

Update configs/config.go. change defaulthost.app.host and
default.app.domain to `localhost`
Update controllers/oauth.go. Use `https://www.twreporte.org/` as default destination
@babygoat

update config.go and oauth.go

---

.circleci/config.yml
CHANGELOG.md

Bump version to 3.0.0

---

controllers/donation.go
controllers/facebook-oauth.go
controllers/google-oauth.go
controllers/oauth.go
glide.lock
glide.yaml
models/donation.go
models/model_user.go
routers/router.go
storage/membership.go
storage/user.go
tests/controller_donations_test.go
utils/helpers.go

 use null library for dealing with nullable SQL and JSON values

---

controllers/donation.go
storage/membership.go
tests/controller_donations_test.go

@babygoat please help to review.

Patch donation functional test

---

controllers/account.go
controllers/oauth.go
utils/token.go

Put `first_name` and `last_name` in id_token JWT claims

---

controllers/account.go

redirect to destination after logout

---

controllers/donation.go
globals/constants.go
membership_user.sql
middlewares/jwt.go
models/donation.go
routers/router.go
storage/donation.go
storage/membership.go
tests/controller_donations_test.go
tests/main_test.go

add three endpoints, including
- `/v1/users/:userID/periodic-donations/:id`, for retrieving a periodic donation according to its `id`
- `/v1/users/:userID/donations/prime/:id`, for retrieving a prime donation according to its `id`
- `/v1/users/:userID/donations/others/:id`, for retrieving a pay by other method donation according to its `id`
**TODO**
`/v1/users/:userID/donations/token/:id`, for retrieving a card token donation according to its `id`

endpoints for retrieving a donation of a user

---

controllers/account.go

This patch fixes the incorrect url endpoint within member activation
mail.

Fix activation url error

---

CHANGELOG.md
controllers/account.go
storage/post.go
storage/topic.go

- Only development environment can return draft posts or topics

Release 3.0.0 with new patch on staging.

---

CHANGELOG.md
configs/config.go
controllers/mail.go
services/mail.go
template/success-donation.tmpl

- Format template/success-donation.tmpl
- Update template/success-donation.tmpl. Add do-not-reply message
- Thank you mail title changed
- Email sender named changed: `no-reply@twreporter.org` -> `報導者 The Reporter <no-reply@twreporter.org>`

Thank you mail refined

---

configs/config.go
controllers/donation.go

This patch adds the forward-proxy in staging/production environment to
perform tappay transaction.

Use forward-proxy to make tappay request

---

configs/config.go

This patch fixes the missing proxy config loading from environment
variables.

Fix missing proxy config

---

CHANGELOG.md
controllers/donation.go
doc/index.html
doc/periodic-donation.apib
doc/prime-donation.apib
membership_user.sql
models/donation.go
tests/controller_donations_test.go

Add anonymity field

---

CHANGELOG.md
template/success-donation.tmpl

This patch updates the success email context according to the feedback
from MKT and curator.

Fine tune the donation success email context

---

CHANGELOG.md

Bump version to 4.0.0

---

controllers/donation.go

This patch improves the error record fields by recordind extra
`rec_trade_id`, `bank_result_code`, `bank_result_msg`
`transaction_time`, `acquirer`, `card_info` and `auth_code`.

Improve error records

---

CHANGELOG.md

Bump version to v5.0.1

---

CHANGELOG.md

This patch updates the CHANGELOG and release 5.0.4.

Release 5.0.4

---

CHANGELOG.md

Release v5.0.4

---

CHANGELOG.md

update CHANGELOG.md current release version

promote v5.1.0-rc.1 to v5.1.0

---

CHANGELOG.md
controllers/index_page.go

This PR is to trigger CircleCI to build and deploy `v5.1.0` on staging environment

Release v5.1.0 on staging branch

---

.circleci/config.yml
CHANGELOG.md
controllers/donation.go
utils/db.go

This PR is to trigger CircleCI to build and deploy `v5.1.1-rc.2` on staging enviroment.

Release v5.1.1-rc.2 on staging

---

CHANGELOG.md

This PR is to trigger CircleCI to build and deploy `v5.1.1` on staging environment

Release v5.1.1 on staging

---

.circleci/config.yml

This patch includes the kubernetes config built from kustomize to deploy
the image to the google kubernetes engine.

Include kubernetes config during deployment

---

.circleci/config.yml

This patch fixes the missing package version file during the environment
setup.

Fix missing package version file

---

.circleci/config.yml

This patch fixes the incorrect context injection on the circleci.

Fix incorrect context injection

---

.circleci/config.yml

This patch fixes the incorrect kustomize PATH.

Fix incorrect kustomize PATH

---

.circleci/config.yml

This patch fixes the incorrect kustomize command to set the image.

Fix incorrect kustomize command

---

CHANGELOG.md
migrations/000005_increase_bank_result_msg_size.down.sql
migrations/000005_increase_bank_result_msg_size.up.sql
models/donation.go

This patch increases the bank_result_msg column size from 50 to 128.

Increase bank_result_msg column

---

.circleci/config.yml

This patch fixes incorrect environment setup on next environment during
k8s config build.

Fix incorrect environment setup

---

.circleci/config.yml
CHANGELOG.md
configs/config.go
controllers/donation.go

Merge master into staging for donation (linepay) frontend host config change.

Merge master into staging

---

controllers/author.go
controllers/news.go
controllers/post.go
controllers/topic.go

This PR is to fix
https://github.com/twreporter/twreporter-npm-packages/issues/88

fix: handle url query parsing failure

---

CHANGELOG.md

Release v6.0.0 on staging

---

CHANGELOG.md

This patch updates the changelog to releases 6.0.1.

Release 6.0.1

---

CHANGELOG.md

This patch updates the changelog to release v6.0.2.

Release v6.0.2

---

CHANGELOG.md

Release v6.0.3

---

CHANGELOG.md

This patch updates the changelog for testing on the staging
environment.

doc: Update Changelog

---

CHANGELOG.md
controllers/mail.go
template/success-donation.tmpl

Support both token donation success and prime donation success

refactor: update success donation email template

---

CHANGELOG.md
migrations/000006_add_receipt_header.down.sql
migrations/000006_add_receipt_header.up.sql

This patch updates schemas of table `pay_by_prime_donations`,
`periodic_donations`, `pay_by_card_token_donations`,
'pay_by_other_method_donations' by adding `receipt_header` column.
Add corresponding `000006_add_receipt_header.down.sql` and
`000006_add_receipt_header.up.sql` for migration.

chore: donations table schema change

---

CHANGELOG.md

This patch updates the CHANGELOG to reflect the change in v6.1.0

Release v6.1.0

---

CHANGELOG.md
internal/mongo/operator.go
internal/news/model.go
internal/news/mongo.go

This patch adds the fix for out-of-order issues of relateds/designers/engineers/photographers on staging for validation.

Validate out-of-order fix on staging

---

CHANGELOG.md
controllers/donation.go
controllers/mail.go
template/success-donation.tmpl

This patch updates donation success email according to the marketing
request changes.
https://docs.google.com/document/d/1GbbGVhckyhSXhTdjOPuZx1wXIbiw2_7oxDY3FsZgsvs
Related to [[story-21][task-1] 調整贊助信個資內容](https://kanbanflow.com/t/RbJT7Gys)

api/mail: update donation success email

---

controllers/donation.go
tests/controller_donations_test.go

This patch returns the status 500 (Internal Server Error) if the
donation record patch failed.

api/donations: return error if patch record failed

---

controllers/news_v2.go
internal/mongo/operator.go
internal/news/model.go
internal/news/mongo.go
internal/news/query.go
routers/router.go
storage/news_v2.go
tests/author_test.go
tests/main_test.go
tests/news_v2_test.go
tests/pre_test_environment_setup.go

Implement v2 author endpoints

---

.circleci/config.yml
CHANGELOG.md

This patch merges master into staging to fix configuration generator issue during deployment

Merge master to staging 

---

CHANGELOG.md

This patch releases go-api v6.2.1.

release v6.2.1

---

controllers/donation.go
doc/donation.apib
doc/index.html
tests/controller_donations_test.go

Address [twreporter-105](https://twreporter-org.atlassian.net/browse/TWREPORTER-105)

api/donation: record api update

---

CHANGELOG.md

This updates the CHANGELOG for release v7.0.1.

chore: release v7.0.1

---

controllers/account.go
doc/auth.apib
doc/index.html

Address [TWREPORTER-199](https://twreporter-org.atlassian.net/browse/TWREPORTER-199)
This patch redirects users to the customized error redirection URL
when error occurs on redirect to destination.

api/account: redirect to the error redirection URL when error occurs

---

doc/index.html
doc/periodic-donation.apib
doc/prime-donation.apib

This patch updates donation docs due to spec change (re-design).

doc: update donation docs due to spec change

---

doc/periodic-donation.apib
doc/prime-donation.apib

This patch updates type of `read_preference` from array of string to
string in doc of (prime|periodic)-donation.

doc: update type of `read_preference`

---

doc/index.html
doc/periodic-donation.apib
doc/prime-donation.apib

- update auto_tx_deduction type to `bool`
- update addres related schema

doc: update prime-donation & periodic-donation doc

---

CHANGELOG.md

This patch updates CHANGELOG to include the changes for v7.1.1

chore: release v7.1.1

---

template/success-donation.tmpl

Address [TWREPORTER-152](https://twreporter-org.atlassian.net/browse/TWREPORTER-152)
This patch updates the email template of success donation due to content
change.
screen shot:

api/mail: update success donation email content

---

CHANGELOG.md

This patch update CHANGELOG.md to release v7.1.2

chore: release 7.1.2

---

CHANGELOG.md

This patch update CHANGELOG.md to release v7.1.3

chore: release 7.1.3

---

configs/config.go
controllers/donation.go
go.mod
go.sum
main.go

- use [slack package](https://github.com/twreporter/go-mod-lib/tree/master/pkg/slack) in go-mod-lib
- add slack webhook conf

feat: add slack notify when publish to cloud pub/sub fail

---

controllers/donation.go
models/donation.go
tests/controller_donations_test.go

This patch add gorm config to store pay_method field.

fix: fix periodic donation do not store pay_method field

---

doc/index.apib
doc/index.html
doc/news/post.apib
doc/news/postcategory.apib
doc/news/tag.apib

- [TWREPORTER-329](https://twreporter-org.atlassian.net/browse/TWREPORTER-329)

docs: update doc for category sets

---

doc/index.html
doc/news/index_page.apib
doc/news/post.apib
doc/news/tag.apib

- post: fix typo
- tag: add `latest_order` & remove `is_latest` parameter

docs: update api doc

---

.circleci/config.yml

This patch fix [gke auth issue](https://app.asana.com/0/1202896150264815/1203605397527512/f).

fix: use gke-gcloud-auth-plugin

---

storage/news_v2.go

Revert "fix sorting"

---

storage/news_v2.go

Revert "fix: sorting large data"

---

controllers/donation.go

This patch fix [[defect] /prime/line-notify 沒接到 neticrm](https://app.asana.com/0/1203699264568808/1204010979844366/f)

fix: endpoint /line-notify publish to neticrm topic

---

CHANGELOG.md

bump version to trigger CI/CD for applying new k8s config

chore: bump version v7.2.4-rc.0

---

CHANGELOG.md

chore: release v7.2.4-rc.0 to staging

---

CHANGELOG.md

[chore: bump version to 7.2.4-rc.1](https://github.com/twreporter/go-api/pull/542)

chore: bump version to 7.2.4-rc.1

---

configs/config.go
controllers/user.go
migrations/000009_add_mailjob_tables_schemas.down.sql
migrations/000009_add_mailjob_tables_schemas.up.sql
models/model_user.go
models/user_preferences.go
routers/router.go
storage/mailgroup.go
storage/membership.go
storage/user.go
tests/controller_user_test.go

New function for setting user's preferences, including maillist related
- only SetUser completed
- GetUser has table join issue
- unit test will be delievered in another commit

feat: Add Mailgroup, SetUser related functions

---

routers/router.go
tests/controller_user_test.go

There was typo in SetUser route

fix: typo for setUser route

---

controllers/account.go
controllers/donation.go
controllers/oauth.go
controllers/user.go
doc/index.html
doc/user.apib
migrations/000012_add_users_activated.down.sql
migrations/000012_add_users_activated.up.sql
models/model_user.go
models/user_preferences.go
routers/router.go
storage/membership.go
storage/user.go

- New API: GetUser
- New migration: activated field in users table
- Modify API: add activated in login response
- Modify API: set activated after set interests and donate step 2
---
- https://app.asana.com/0/0/1204378944314708
- https://app.asana.com/0/0/1204692921007278

feat: implement GetUser API and activated status

---

CHANGELOG.md

chore: bump version to 7.2.4-rc.3

---

CHANGELOG.md

chore: bump version to 7.2.4-rc.4

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.7

---

controllers/account.go
controllers/donation.go
controllers/mail.go
globals/constants.go
routers/router.go
storage/membership.go
storage/user.go
template/role-actiontaker.tmpl
template/role-downgrade.tmpl
template/role-explorer.tmpl
template/role-trailblazer.tmpl

Add role assign related mails:
- send_role_explorer
- send_role_actiontaker
- send_role_trailblazer
- send_role_downgrade (only route, for cronjob implemented in later task)
---
- https://app.asana.com/0/0/1204934606026369

feat: Add role assign related mails

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.8

---

controllers/controller-factory.go
controllers/donation.go
storage/user.go

The role assign mail templates were not loaded.
---
- https://app.asana.com/0/0/1205230308764714
- https://app.asana.com/0/0/1205230308764715
- https://app.asana.com/0/0/1205230316281159

fix: role assign mail templates loader

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.9

---

storage/user.go

The IsTrailblazer sometimes failed

fix: change IsTrailblazer SQL condition

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.10

---

template/role-actiontaker.tmpl
template/role-downgrade.tmpl
template/role-explorer.tmpl
template/role-trailblazer.tmpl

The `*|MC_PREVIEW_TEXT|*`is currently not using.

fix: remove unused string from template

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.11

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.12

---

CHANGELOG.md
controllers/user.go
template/role-trailblazer.tmpl

chore: test 7.2.4-rc.13 on staging 

---

configs/config.go
controllers/mail.go

Add feature toggle for sendRoleMail.

feat: Add feature toggle for sendRoleMail

---

CHANGELOG.md

chore: bump version to v7.2.4-rc.14

---

CHANGELOG.md
configs/config.go
controllers/mail.go
template/role-trailblazer.tmpl

chore: test 7.2.4-rc.14 on staging 

---

controllers/account.go

chore: merge master into staging for testing

---

configs/config.go
controllers/account.go

Fix the loading of mailchimp related env

fix: mailchimp interest id env

---

CHANGELOG.md

chore: bump version to v7.3.1

---

CHANGELOG.md
configs/config.go
controllers/account.go

chore: test v7.3.1 on staging 

---

CHANGELOG.md

chore: bump version to v7.3.3

---

controllers/donation.go

fix: LinePay role mail when success

---

CHANGELOG.md

chore: bump version to v7.3.4-rc.0

---

CHANGELOG.md
controllers/donation.go

chore: test v7.3.4-rc.0 on staging 

---

CHANGELOG.md

chore: bump version to v7.3.4

---

storage/user.go

Fix isTrailblazer sql logic from `pd` to `p`

fix: isTrailblazer sql logic

---

CHANGELOG.md

chore: bump version to v7.3.5-rc.0 

---

CHANGELOG.md
controllers/donation.go
storage/user.go

chore: test v7.3.5-rc.0 on staging

---

controllers/account.go
controllers/controller-factory.go
controllers/mail.go
globals/constants.go
routers/router.go
template/signin-otp.tmpl

Add OTP login APIs
- /v1/mail/send_otp
- /v3/auth/signin
- /v3/auth/activate
---
- https://app.asana.com/0/0/1204934606026373

feat: Add OTP login APIs

---

CHANGELOG.md

chore: bump version to v7.3.5-rc.1

---

CHANGELOG.md
storage/user.go

chore: release v7.3.5-rc.0 on production 

---

controllers/account.go

send same activeToken in 5 min for signin
---
- https://app.asana.com/0/0/1205413135009481

feat: send same activeToken in 5 min for signin

---

CHANGELOG.md

chore: bump version to v7.3.5

---

CHANGELOG.md

fix: add missing CHANGELOG

---

template/role-trailblazer.tmpl

fix typo in trailblazer mail
---
- https://app.asana.com/0/0/1205912735270104

fix: typo in trailblazer template

---

CHANGELOG.md

chore: bump version to v7.3.6-rc.0

---

CHANGELOG.md
template/role-trailblazer.tmpl

 chore: test v7.3.6-rc.0 on staging 

---

CHANGELOG.md

chore: bump version to v7.3.6

---

CHANGELOG.md

chore: test v7.3.6 on staging 

---

controllers/donation.go
tests/controller_donations_test.go

[[贊助流程] 信用卡授權失敗 error message-後端](https://app.asana.com/0/1203699264568808/1206044219917221/f)
N/A

fix: return 400 when card error (10003)

---

CHANGELOG.md
controllers/news_v2.go
internal/news/category.go

[報導者首頁「評論」區塊未顯示最新文章](https://app.asana.com/0/0/1206238664023561/f)

fix: use new category_set key for review section

---

controllers/controller-factory.go
controllers/news_v2.go
doc/news/post.apib
internal/news/model.go
middlewares/jwt.go
routers/router.go
storage/news_v2.go
tests/news_v2_test.go

[[會員制] 我的閱讀 - 最新頁新增收藏功能](https://app.asana.com/0/1203699264568808/1206201445527861/f)
- add `PassAuthUserID` middleware to store user id in context
- add gorm (sql db) storage for newsV2 controllers
- add `GetBookmarkFromPosts` to get bookmark id from userId & post slug
N/A

feat: add bookmarkId in /posts if user is authed

---

CHANGELOG.md
migrations/000017_increase_bookmarks_slug_size.down.sql
migrations/000017_increase_bookmarks_slug_size.up.sql

[[維運] 文章頁收藏相關問題](https://app.asana.com/0/1203699264568808/1206379506612355/f)

fix: upgrade bookmarks slug size

---

controllers/analytics.go
doc/user.apib
internal/news/model.go
internal/news/mongo.go
migrations/000018_update_users_bookmarks_schema.down.sql
migrations/000018_update_users_bookmarks_schema.up.sql
models/bookmark.go
models/users_bookmarks.go
storage/analytics.go
tests/controller_analytics_test.go

[[會員制] 我的閱讀：造訪紀錄串接後端](https://app.asana.com/0/1203699264568808/1206438266608910/f)
tbd: migration of `post_id` value in users_bookmarks
N/A

feat: add bookmark_id in meta of footprint

---

migrations/000019_change_ntch_roles.down.sql
migrations/000019_change_ntch_roles.up.sql

The NTCH collaboration roles incorrect
Keep the old role key for fallback compatibility.  Should be remove in the future.

fix: change ntch roles

---

CHANGELOG.md
controllers/news_v2.go
migrations/000019_change_ntch_roles.down.sql
migrations/000019_change_ntch_roles.up.sql

chore: test v7.5.1-rc.2 on staging 

---

controllers/news_v2.go
doc/index.html
doc/news/post.apib

[[defect] 最新頁無正常顯示收藏文章](https://app.asana.com/0/1203699264568808/1206633978405324/f)
N/A

fix: add `toggleBookmark` to address cache provlem for /v2/posts

---

CHANGELOG.md
controllers/news_v2.go
doc/index.html
doc/news/index_page.apib
doc/news/post.apib
internal/news/model.go
internal/news/mongo.go
tests/news_v2_test.go

[[維運] 清除資訊架構新舊相容的 code](https://app.asana.com/0/1203699264568808/1206398708372264/f)

feat: remove old category

---

controllers/news_v2.go
internal/news/query.go
internal/news/query_test.go

- /index_page opinion & photography section posts wrong
- /posts query with category & without subcategory would get wrong posts
N/A

fix: query with category_set instead of categories

---

controllers/analytics.go
tests/controller_analytics_test.go

[[維運]閱讀時間設定上限](https://app.asana.com/0/1203699264568808/1206861124078197/f)
N/A

fix: set exceed read posts seconds to 7200

---

controllers/account.go

[[defect] 未填寫興趣的會員需再次進入onbording 流程](https://app.asana.com/0/0/1207097463587683/f)
N/A

fix: clear `activated` cookie when logout

---

CHANGELOG.md
controllers/donation.go
tests/controller_donations_test.go

[[維運]  信用卡授權失敗（卡片過期）-後端](https://app.asana.com/0/1203699264568808/1206827670326358/f)

feat: add error code for card expired

---

CHANGELOG.md

chore: bump version to v7.5.5

---

template/role-actiontaker.tmpl
template/role-trailblazer.tmpl

[[維運] 更新歡迎成為「開創者」、「行動者」信件內容](https://app.asana.com/0/1203699264568808/1207412719435367/f)
N/A

fix: update role email template

---

migrations/000020_add_receipt_no_column.down.sql
migrations/000020_add_receipt_no_column.up.sql

[go api-開立收據編號欄位](https://app.asana.com/0/1205812314629275/1207537656691262/f)
[Schema docs](https://www.notion.so/twreporter/pay_by_prime_donations-b4e2927d173543fdb961c9c69c5b3506?pvs=4)

feat: Add receipt number column for donations

---

CHANGELOG.md

chore: bump version to v7.5.6-rc.2

---

CHANGELOG.md
storage/news_v2.go

[[維運] redux 升級後續 refactor: 書籤](https://app.asana.com/0/1203699264568808/1207639742964814/f) defects

fix: use First to find bookmark and dont return err while not found

---

internal/news/mongo.go

[[defect] 後續追蹤內容排序和後台設定不相符，也未依照由舊至新的邏輯排序](https://app.asana.com/0/1203699264568808/1207764753093381/f)
N/A

fix: followup should be order preserved field

---

CHANGELOG.md
internal/news/mongo.go
storage/news_v2.go
tests/author_test.go

[[defect] 作者頁超連結顯示不正常且無效](https://app.asana.com/0/1202936421725081/1207793339880766/f)

feat: return html instead md

---

CHANGELOG.md

chore: bump version to v7.5.7

---

controllers/donation.go
migrations/000021_add_receipt_serial_number_table.down.sql
migrations/000021_add_receipt_serial_number_table.up.sql
models/donation.go
storage/donation.go
storage/membership.go

[[電子收據] 贊助完成由系統自動建立單筆贊助編號
](https://app.asana.com/0/1203699264568808/1207629974038946/f)
also add migrations for `receipt_serial_numbers` table
N/A

feat: generate receipt serail number for prime

---

CHANGELOG.md

chore: bump version to v7.5.9

---

controllers/mail.go
template/signin-otp.tmpl

[[維運]系統信統一視覺-OTP通知信](https://app.asana.com/0/1203699264568808/1208110637254088/f)
N/A

fix: update otp mail template

---

template/signin-otp.tmpl

[[defect/change spec] 字體大小不一致/修正信件內容
](https://app.asana.com/0/1203699264568808/1208279921606018/f)
N/A

fix: style & wording of otp mail template

---

internal/mongo/document.go
tests/news_v2_test.go

[[debug]報導追蹤，可顯示項目超過三個月](https://app.asana.com/0/1203699264568808/1208375665334458/f)
N/A

fix: only return last 3 month followups

---

configs/config.go
configs/constants/constants.go
controllers/test.go
internal/graphql/client.go
internal/graphql/method.go
main.go
routers/router.go

[[電子收據] go-api 對接 member cms ](https://app.asana.com/0/1203699264568808/1208301216504807/f)
please add member cms auth info in config.go before testing
N/A

feat: add graphql client for member cms interface

---

configs/config.go
internal/graphql/method.go

[[電子收據] go-api 對接 member cms](https://app.asana.com/0/1203699264568808/1208301216504807/f) 
N/A

fix: add `session_max_age` config

---

configs/config.go
internal/graphql/method.go

add feature toggle for [[電子收據] go-api 對接 member cms ](https://app.asana.com/0/1203699264568808/1208301216504807/f)
N/A

fix: add feature toggle for integrating with member cms

---

template/success-donation-periodic.tmpl
template/success-donation-prime.tmpl

[[defect] 桌機版畫面未顯示 CSS 樣式](https://app.asana.com/0/1203699264568808/1208633431793894/f)
N/A

fix: template link style

---

internal/member_cms/graphql.go

fix: incorrect `host` value

---

storage/donation.go

[[defect]贊助編號錯誤](https://app.asana.com/0/1203699264568808/1208932302134909/f)
N/A

fix: specific timezone for receipt number

---

template/role-actiontaker.tmpl
template/role-downgrade.tmpl
template/role-explorer.tmpl
template/role-trailblazer.tmpl

[[維運]支持方案優惠更新](https://www.notion.so/twreporter/1658dbdca9328024a440cca4e293a7ec?pvs=4)
N/A

fix: update role mail template

---

template/role-trailblazer.tmpl

[[defect] 開創者文案不完整](https://www.notion.so/twreporter/defect-18f8dbdca9328082a11ff1ee47bcf5d1?pvs=4)
N/A

fix: rol-trailblazer template wording

---

CHANGELOG.md

chore: bump version to 7.7.3

---

CHANGELOG.md

chore: test v7.7.3 on staging

---

CHANGELOG.md

chore: bump version to v7.7.3-rc.0

---

controllers/news_v2.go
internal/news/query.go
internal/news/tag.go

[[維運] 首頁多媒體區塊串接資料修正](https://www.notion.so/twreporter/1b28dbdca93280d19395efdc128ce005?source=copy_link)
N/A

fix: get infographic tag instead of filter style

---

migrations/000023_add_show_offline_donation_to_user.down.sql
migrations/000023_add_show_offline_donation_to_user.up.sql

feat: add is_showofflinedonation column to users table

---

CHANGELOG.md

chore: bump version to v7.7.6-rc.0

---

configs/config.go
controllers/donation.go
storage/donation.go
storage/membership.go

add feature toggle for [[維運] 贊助紀錄新增線下贊助-後端](https://www.notion.so/twreporter/2228dbdca93280f992d8c28ed9bc80e9?source=copy_link)
N/A

feat: add feature toggle for offline donation

---

controllers/user.go
storage/membership.go
storage/user.go
tests/controller_user_test.go

[[維運] 專屬回饋頁新增定期定額身份區塊](https://www.notion.so/twreporter/2308dbdca9328005b307c214535cc202?source=copy_link)
N/A

feat: add `IsPeriodicPatron` func

---

CHANGELOG.md

chore: bump version to v7.7.8-rc.1

---

CHANGELOG.md

chore: bump version to v7.7.8
